<?php

namespace App\Console\Commands;

use Closure;
use Illuminate\Console\Command;
use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Laravel\Fortify\Features;
use ReflectionClass;
use ReflectionFunction;
use Symfony\Component\Finder\SplFileInfo;

/**
 * Captures the implementation-state inventory Phase 0 requires before exit.
 *
 * The point is a factual as-built record, not a design document: what the system
 * *is* on the day Phase 0 closes, so Phase 1 starts from a known line and later
 * drift is a diff rather than an argument. It is generated rather than written
 * for the same reason — a hand-written inventory is out of date the first time
 * anyone adds a column.
 *
 * Only structure is captured. Row counts and which migrations have run are
 * per-environment facts that would make the document differ between machines,
 * so they are deliberately excluded and `--check` stays meaningful.
 */
class CaptureBaselineInventory extends Command
{
    protected $signature = 'inventory:baseline
        {--check : Regenerate and fail if the committed inventory has drifted}';

    protected $description = 'Capture the Phase 0 baseline inventory of schema, routes, authentication, module boundaries, CI gates and deployment targets';

    private const OUTPUT = 'docs/phase-0/baseline-inventory.md';

    public function handle(): int
    {
        $rendered = $this->render();
        $path = base_path(self::OUTPUT);

        if (! $this->option('check')) {
            File::ensureDirectoryExists(dirname($path));
            File::put($path, $rendered);

            $this->components->info('Baseline inventory written to '.self::OUTPUT);

            return self::SUCCESS;
        }

        if (! File::exists($path)) {
            $this->components->error(self::OUTPUT.' is missing. Run `php artisan inventory:baseline`.');

            return self::FAILURE;
        }

        if (File::get($path) !== $rendered) {
            $this->components->error(
                self::OUTPUT.' has drifted from the code it describes. Run `php artisan inventory:baseline` and commit the result.'
            );

            return self::FAILURE;
        }

        $this->components->info('Baseline inventory matches the code it describes.');

        return self::SUCCESS;
    }

    private function render(): string
    {
        return implode("\n", [
            '# Phase 0 baseline inventory',
            '',
            'Generated by `php artisan inventory:baseline`. Do not edit by hand — `--check` runs in CI',
            'and fails when this file no longer describes the code.',
            '',
            'This is an as-built record of what the system **is**, so Phase 1 starts from a known line.',
            'It captures structure only. Row counts and which migrations have run are per-environment',
            'facts that would differ between machines, so they are excluded deliberately.',
            '',
            $this->runtimeSection(),
            $this->schemaSection(),
            $this->migrationsSection(),
            $this->routesSection(),
            $this->authenticationSection(),
            $this->boundariesSection(),
            $this->gatesSection(),
            $this->deploymentSection(),
        ])."\n";
    }

    private function runtimeSection(): string
    {
        /** @var array<string, mixed> $composer */
        $composer = json_decode((string) File::get(base_path('composer.json')), true, 512, JSON_THROW_ON_ERROR);

        $rows = [
            ['PHP (declared)', (string) $composer['require']['php']],
            ['Laravel', app()->version()],
            ['Node (pinned)', trim((string) File::get(base_path('.node-version')))],
            ['Default database connection', (string) config('database.default')],
            ['Concurrency-authoritative connection', 'pgsql (D-73)'],
        ];

        return $this->markdownTable('## Runtime contract', ['Item', 'Value'], $rows);
    }

    private function schemaSection(): string
    {
        $out = ['## Schema', ''];

        foreach ($this->sortedTables() as $table) {
            $out[] = '### `'.$table.'`';
            $out[] = '';
            $out[] = '| Column | Type | Nullable | Default |';
            $out[] = '|---|---|---|---|';

            foreach (Schema::getColumns($table) as $column) {
                $out[] = sprintf(
                    '| `%s` | `%s` | %s | %s |',
                    $column['name'],
                    $column['type_name'],
                    $column['nullable'] ? 'yes' : 'no',
                    $column['default'] === null ? '—' : '`'.$column['default'].'`',
                );
            }

            $indexes = collect(Schema::getIndexes($table))
                ->sortBy('name')
                ->map(fn (array $index): string => sprintf(
                    '`%s` on (%s)%s',
                    $index['name'],
                    implode(', ', $index['columns']),
                    $index['unique'] ? ' — unique' : '',
                ))
                ->all();

            $out[] = '';
            $out[] = '**Indexes:** '.($indexes === [] ? 'none' : implode('; ', $indexes));
            $out[] = '';
        }

        return implode("\n", $out);
    }

    private function migrationsSection(): string
    {
        $files = array_values(collect(File::files(database_path('migrations')))
            ->map(fn ($file): string => $file->getFilename())
            ->sort()
            ->map(fn (string $name): array => [$name])
            ->all());

        return $this->markdownTable(
            '## Migrations',
            ['File'],
            $files,
            'Files present in `database/migrations`. Which of these have run is per-environment and not captured here.',
        );
    }

    private function routesSection(): string
    {
        $rows = array_values(collect(Route::getRoutes()->getRoutes())
            ->reject(fn (RoutingRoute $route): bool => $this->isVendorRoute($route))
            ->sortBy(fn (RoutingRoute $route): string => $route->uri().' '.implode(',', $route->methods()))
            ->map(fn (RoutingRoute $route): array => [
                implode('|', array_diff($route->methods(), ['HEAD'])),
                '`/'.ltrim($route->uri(), '/').'`',
                $route->getName() === null ? '—' : '`'.$route->getName().'`',
                '`'.$this->routeAction($route).'`',
                implode(', ', $route->gatherMiddleware()) ?: '—',
            ])
            ->all());

        return $this->markdownTable('## Routes', ['Method', 'URI', 'Name', 'Action', 'Middleware'], $rows, 'Vendor routes excluded, matching `route:list --except-vendor`.');
    }

    private function authenticationSection(): string
    {
        $features = collect([
            Features::registration() ? 'registration' : null,
            Features::resetPasswords() ? 'reset-passwords' : null,
            Features::emailVerification() ? 'email-verification' : null,
            Features::updateProfileInformation() ? 'update-profile-information' : null,
            Features::updatePasswords() ? 'update-passwords' : null,
            Features::twoFactorAuthentication() ? 'two-factor-authentication' : null,
        ])->filter()->sort()->values()->implode(', ');

        /** @var array<string, array<string, mixed>> $guards */
        $guards = config('auth.guards');
        /** @var array<string, array<string, mixed>> $providers */
        $providers = config('auth.providers');

        $rows = [
            ['Fortify features', $features === '' ? 'none' : $features],
            ['Default guard', (string) config('auth.defaults.guard')],
            ['Guards', collect($guards)->map(fn (array $g, string $n): string => "{$n} ({$g['driver']})")->sort()->implode(', ')],
            ['Providers', collect($providers)->map(fn (array $p, string $n): string => "{$n} ({$p['driver']})")->sort()->implode(', ')],
            ['Password broker expiry', (string) config('auth.passwords.users.expire').' minutes'],
        ];

        return $this->markdownTable('## Authentication', ['Item', 'Value'], $rows);
    }

    private function boundariesSection(): string
    {
        $layers = [
            'Domain' => 'app/Domain',
            'Application' => 'app/Application',
            'Infrastructure' => 'app/Infrastructure',
            'HTTP — controllers' => 'app/Http/Controllers',
            'HTTP — requests' => 'app/Http/Requests',
            'HTTP — resources' => 'app/Http/Resources',
            'HTTP — middleware' => 'app/Http/Middleware',
            'Models' => 'app/Models',
            'Console commands' => 'app/Console/Commands',
        ];

        $rows = [];

        foreach ($layers as $label => $directory) {
            $classes = collect(File::allFiles(base_path($directory)))
                ->map(fn ($file): string => Str::of($file->getPathname())
                    ->after(base_path($directory).DIRECTORY_SEPARATOR)
                    ->replace(DIRECTORY_SEPARATOR, '\\')
                    ->replace('.php', '')
                    ->toString())
                ->sort()
                ->values();

            $rows[] = [
                $label,
                '`'.$directory.'`',
                (string) $classes->count(),
                $classes->isEmpty() ? '—' : '`'.$classes->implode('`, `').'`',
            ];
        }

        return $this->markdownTable(
            '## Module boundaries',
            ['Layer', 'Path', 'Classes', 'Contents'],
            $rows,
            'The ADR-0001 layering as it stands. `tests/Architecture` enforces the dependency direction between these.',
        );
    }

    private function gatesSection(): string
    {
        $rows = [];

        foreach ($this->workflowFiles() as $file) {
            $contents = (string) File::get($file->getPathname());

            preg_match('/^name:\s*(.+)$/m', $contents, $workflowName);
            preg_match_all('/^  ([a-z0-9_-]+):$/m', $contents, $jobs);
            preg_match_all('/^\s{4}name:\s*(.+)$/m', $contents, $jobNames);

            $rows[] = [
                '`'.$file->getFilename().'`',
                trim($workflowName[1] ?? '—'),
                implode(', ', $jobs[1]) ?: '—',
                implode('; ', array_map(trim(...), $jobNames[1])) ?: '—',
            ];
        }

        return $this->markdownTable('## CI gates', ['Workflow', 'Name', 'Jobs', 'Job titles'], $rows);
    }

    private function deploymentSection(): string
    {
        $rows = [];

        foreach ($this->workflowFiles() as $file) {
            $contents = (string) File::get($file->getPathname());

            if (! str_contains($contents, 'deploy-remote.sh')) {
                continue;
            }

            preg_match('/^name:\s*(.+)$/m', $contents, $name);
            preg_match('/branches:\s*\[([a-z]+)\]/', $contents, $branch);
            preg_match("/bash -s -- (\S+)' </", $contents, $root);
            preg_match_all('/secrets\.([A-Z0-9_]+)/', $contents, $secrets);

            $rows[] = [
                trim($name[1] ?? '—'),
                '`'.($branch[1] ?? '—').'`',
                '`'.($root[1] ?? '—').'`',
                implode(', ', array_unique($secrets[1])) ?: '—',
            ];
        }

        return $this->markdownTable(
            '## Deployment targets',
            ['Environment', 'Branch', 'Server path', 'Required secrets'],
            $rows,
            'Secret **names** only — never values. Both environments run behind the D-68 admission gate and pin PHP 8.5 at deploy time.',
        );
    }

    /**
     * @return list<SplFileInfo>
     */
    private function workflowFiles(): array
    {
        return array_values(collect(File::files(base_path('.github/workflows')))
            ->filter(fn (SplFileInfo $file): bool => $file->getExtension() === 'yml')
            ->sortBy(fn (SplFileInfo $file): string => $file->getFilename())
            ->all());
    }

    /**
     * @return list<string>
     */
    private function sortedTables(): array
    {
        return array_values(collect(Schema::getTables())
            ->map(fn (array $table): string => (string) $table['name'])
            ->sort()
            ->all());
    }

    private function routeAction(RoutingRoute $route): string
    {
        $uses = $route->action['uses'] ?? null;

        if ($uses instanceof Closure || ! is_string($uses)) {
            return 'Closure';
        }

        return Str::after($uses, 'App\\Http\\Controllers\\');
    }

    /**
     * Mirrors RouteListCommand::isVendorRoute so this inventory and
     * `route:list --except-vendor` never disagree about what is first-party.
     */
    private function isVendorRoute(RoutingRoute $route): bool
    {
        $uses = $route->action['uses'] ?? null;

        $file = $uses instanceof Closure
            ? (new ReflectionFunction($uses))->getFileName()
            : $this->controllerFileName($route->getControllerClass());

        return is_string($file) && str_starts_with($file, base_path('vendor'));
    }

    /**
     * The file a controller is declared in, or null when the route has no
     * controller class to reflect on.
     */
    private function controllerFileName(?string $controller): ?string
    {
        return $controller !== null && class_exists($controller)
            ? ((new ReflectionClass($controller))->getFileName() ?: null)
            : null;
    }

    /**
     * @param  list<string>  $headings
     * @param  list<list<string>>  $rows
     */
    private function markdownTable(string $heading, array $headings, array $rows, ?string $note = null): string
    {
        $out = [$heading, ''];

        if ($note !== null) {
            $out[] = $note;
            $out[] = '';
        }

        $out[] = '| '.implode(' | ', $headings).' |';
        $out[] = '|'.str_repeat('---|', count($headings));

        foreach ($rows as $row) {
            $out[] = '| '.implode(' | ', $row).' |';
        }

        $out[] = '';

        return implode("\n", $out);
    }
}
