import inertia from '@inertiajs/vite';
import { wayfinder } from '@laravel/vite-plugin-wayfinder';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import laravel from 'laravel-vite-plugin';
import { bunny } from 'laravel-vite-plugin/fonts';
import { defineConfig, lazyPlugins } from 'vite-plus';

export default defineConfig({
    staged: {
        '*': 'vp check --fix',
    },
    lint: {
        plugins: ['oxc', 'typescript', 'unicorn', 'react', 'import'],
        jsPlugins: [
            '@stylistic/eslint-plugin',
            {
                name: 'vite-plus',
                specifier: 'vite-plus/oxlint-plugin',
            },
        ],
        categories: {
            correctness: 'warn',
        },
        env: {
            browser: true,
            builtin: true,
        },
        ignorePatterns: [
            '.agents/**',
            '.claude/**',
            '.github/**',
            '.vite-hooks/**',
            '.vscode/**',
            'bootstrap/cache/**',
            'bootstrap/ssr/**',
            'coverage/**',
            'docs/**',
            'graphify-out/**',
            'node_modules/**',
            'public/**',
            'storage/**',
            'vendor/**',
            'tailwind.config.js',
            'vite.config.ts',
            'resources/js/actions/**',
            'resources/js/routes/**',
            'resources/js/wayfinder/**',
        ],
        rules: {
            'constructor-super': 'error',
            curly: ['error', 'all'],
            'for-direction': 'error',
            'getter-return': 'error',
            'no-async-promise-executor': 'error',
            'no-case-declarations': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': 'error',
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-delete-var': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': 'error',
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-empty-static-block': 'error',
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-global-assign': 'error',
            'no-import-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-obj-calls': 'error',
            'no-prototype-builtins': 'error',
            'no-redeclare': 'error',
            'no-regex-spaces': 'error',
            'no-self-assign': 'error',
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-this-before-super': 'error',
            'no-undef': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': 'error',
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'error',
            'no-with': 'error',
            'require-yield': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'no-array-constructor': 'error',
            'no-unused-expressions': 'error',
            'import/consistent-type-specifier-style': [
                'error',
                'prefer-top-level',
            ],
            '@stylistic/padding-line-between-statements': [
                'error',
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'if',
                },
                {
                    blankLine: 'always',
                    prev: 'if',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'return',
                },
                {
                    blankLine: 'always',
                    prev: 'return',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'for',
                },
                {
                    blankLine: 'always',
                    prev: 'for',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'while',
                },
                {
                    blankLine: 'always',
                    prev: 'while',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'do',
                },
                {
                    blankLine: 'always',
                    prev: 'do',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'switch',
                },
                {
                    blankLine: 'always',
                    prev: 'switch',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'try',
                },
                {
                    blankLine: 'always',
                    prev: 'try',
                    next: '*',
                },
                {
                    blankLine: 'always',
                    prev: '*',
                    next: 'throw',
                },
                {
                    blankLine: 'always',
                    prev: 'throw',
                    next: '*',
                },
            ],
            '@stylistic/brace-style': [
                'error',
                '1tbs',
                {
                    allowSingleLine: false,
                },
            ],
            'react/rules-of-hooks': 'error',
            'react/exhaustive-deps': 'error',
            'react/static-components': 'error',
            'react/use-memo': 'error',
            'react/void-use-memo': 'error',
            'react/preserve-manual-memoization': 'error',
            'react/immutability': 'error',
            'react/globals': 'error',
            'react/refs': 'error',
            'react/set-state-in-effect': 'error',
            'react/error-boundaries': 'error',
            'react/purity': 'error',
            'react/set-state-in-render': 'error',
            'react/unsupported-syntax': 'warn',
            'typescript/ban-ts-comment': 'error',
            'typescript/no-duplicate-enum-values': 'error',
            'typescript/no-empty-object-type': 'error',
            'typescript/no-explicit-any': 'off',
            'typescript/no-extra-non-null-assertion': 'error',
            'typescript/no-misused-new': 'error',
            'typescript/no-namespace': 'error',
            'typescript/no-non-null-asserted-optional-chain': 'error',
            'typescript/no-require-imports': 'error',
            'typescript/no-this-alias': 'error',
            'typescript/no-unnecessary-type-constraint': 'error',
            'typescript/no-unsafe-declaration-merging': 'error',
            'typescript/no-unsafe-function-type': 'error',
            'typescript/no-wrapper-object-types': 'error',
            'typescript/prefer-as-const': 'error',
            'typescript/prefer-namespace-keyword': 'error',
            'typescript/triple-slash-reference': 'error',
            'typescript/consistent-type-imports': [
                'error',
                {
                    prefer: 'type-imports',
                    fixStyle: 'separate-type-imports',
                },
            ],
            'vite-plus/prefer-vite-plus-imports': 'error',
        },
        overrides: [
            {
                files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
                rules: {
                    'constructor-super': 'off',
                    'getter-return': 'off',
                    'no-class-assign': 'off',
                    'no-const-assign': 'off',
                    'no-dupe-class-members': 'off',
                    'no-dupe-keys': 'off',
                    'no-func-assign': 'off',
                    'no-import-assign': 'off',
                    'no-new-native-nonconstructor': 'off',
                    'no-obj-calls': 'off',
                    'no-redeclare': 'off',
                    'no-setter-return': 'off',
                    'no-this-before-super': 'off',
                    'no-undef': 'off',
                    'no-unreachable': 'off',
                    'no-unsafe-negation': 'off',
                    'no-var': 'error',
                    'no-with': 'off',
                    'prefer-const': 'error',
                    'prefer-rest-params': 'error',
                    'prefer-spread': 'error',
                },
            },
            {
                files: ['tests/web/**/*.{ts,tsx}'],
                rules: {
                    'testing-library/await-async-events': [
                        'error',
                        {
                            eventModule: 'userEvent',
                        },
                    ],
                    'testing-library/await-async-queries': 'error',
                    'testing-library/await-async-utils': 'error',
                    'testing-library/no-await-sync-events': [
                        'error',
                        {
                            eventModules: ['fire-event'],
                        },
                    ],
                    'testing-library/no-await-sync-queries': 'error',
                    'testing-library/no-container': 'error',
                    'testing-library/no-debugging-utils': 'warn',
                    'testing-library/no-dom-import': ['error', 'react'],
                    'testing-library/no-global-regexp-flag-in-query': 'error',
                    'testing-library/no-manual-cleanup': 'error',
                    'testing-library/no-node-access': 'error',
                    'testing-library/no-promise-in-fire-event': 'error',
                    'testing-library/no-render-in-lifecycle': 'error',
                    'testing-library/no-unnecessary-act': 'error',
                    'testing-library/no-wait-for-multiple-assertions': 'error',
                    'testing-library/no-wait-for-side-effects': 'error',
                    'testing-library/no-wait-for-snapshot': 'error',
                    'testing-library/prefer-find-by': 'error',
                    'testing-library/prefer-presence-queries': 'error',
                    'testing-library/prefer-query-by-disappearance': 'error',
                    'testing-library/prefer-screen-queries': 'error',
                    'testing-library/render-result-naming-convention': 'error',
                    'jest-dom/prefer-checked': 'error',
                    'jest-dom/prefer-empty': 'error',
                    'jest-dom/prefer-enabled-disabled': 'error',
                    'jest-dom/prefer-focus': 'error',
                    'jest-dom/prefer-in-document': 'error',
                    'jest-dom/prefer-required': 'error',
                    'jest-dom/prefer-to-have-attribute': 'error',
                    'jest-dom/prefer-to-have-class': 'error',
                    'jest-dom/prefer-to-have-style': 'error',
                    'jest-dom/prefer-to-have-text-content': 'error',
                    'jest-dom/prefer-to-have-value': 'error',
                },
                jsPlugins: [
                    'eslint-plugin-testing-library',
                    'eslint-plugin-jest-dom',
                ],
            },
        ],
        options: {
            typeAware: true,
            // Vite+ 0.3 does not discover the separate test TypeScript project.
            // The `types:check` script remains authoritative for both projects.
            typeCheck: false,
        },
    },
    fmt: {
        semi: true,
        singleQuote: true,
        singleAttributePerLine: false,
        htmlWhitespaceSensitivity: 'css',
        overrides: [
            {
                files: ['tests/web/shell/layouts-and-pages.test.tsx'],
                options: {
                    // Preserve the prior import/order comparator for nested layouts.
                    sortImports: false,
                },
            },
        ],
        printWidth: 80,
        tabWidth: 4,
        sortPackageJson: false,
        sortImports: {
            groups: [
                ['builtin', 'type-builtin'],
                ['external', 'type-external'],
                ['internal', 'type-internal'],
                ['parent', 'type-parent'],
                ['sibling', 'type-sibling'],
                ['index', 'type-index'],
                'style',
                'unknown',
            ],
            ignoreCase: true,
            newlinesBetween: false,
            partitionByNewline: true,
        },
        sortTailwindcss: {
            stylesheet: 'resources/css/app.css',
            functions: ['clsx', 'cn', 'cva'],
        },
        ignorePatterns: [
            '.agents/**',
            '.claude/**',
            '.github/**',
            '.vite-hooks/**',
            '.vscode/**',
            '*.md',
            '.mcp.json',
            'bootstrap/cache/**',
            'bootstrap/ssr/**',
            'boost.json',
            'coverage/**',
            'docs/**',
            'graphify-out/**',
            'node_modules/**',
            'pnpm-workspace.yaml',
            'public/**',
            'storage/**',
            'vendor/**',
            'resources/views/mail/**',
            'resources/js/actions/**',
            'resources/js/routes/**',
            'resources/js/wayfinder/**',
        ],
    },
    plugins: lazyPlugins(() => [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.tsx'],
            refresh: true,
            fonts: [
                bunny('Instrument Sans', {
                    weights: [400, 500, 600],
                }),
                bunny('Inter', {
                    weights: [400, 500, 600, 700, 800],
                }),
            ],
        }),
        inertia(),
        react({
            babel: {
                plugins: ['babel-plugin-react-compiler'],
            },
        }),
        tailwindcss(),
        wayfinder({
            formVariants: true,
        }),
    ]),
});
